// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYuPPfKQEDj20qoroOFazclOwCCEZgaxY',
    appId: '1:835586040680:web:421ffc973b75c0a174ecdd',
    messagingSenderId: '835586040680',
    projectId: 'zikr-ae3a0',
    authDomain: 'zikr-ae3a0.firebaseapp.com',
    storageBucket: 'zikr-ae3a0.appspot.com',
    measurementId: 'G-59DQNSJXDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHOb_VSJPGg4GmdrKbweEeeACtV4hegsk',
    appId: '1:835586040680:android:413093cc9a26447d74ecdd',
    messagingSenderId: '835586040680',
    projectId: 'zikr-ae3a0',
    storageBucket: 'zikr-ae3a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjucsBSvTcbj1yqDrwVC2pgBaO7D-p1G8',
    appId: '1:835586040680:ios:6ad2f5f40e87a5f574ecdd',
    messagingSenderId: '835586040680',
    projectId: 'zikr-ae3a0',
    storageBucket: 'zikr-ae3a0.appspot.com',
    iosClientId: '835586040680-r3tmo9be8vmb341f7i814rqsgau56mk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.zikr',
  );
}
